INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('1', '1', 'Superbe tarte au citron', 'nain connu', '5');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('2', '1', 'Bof', 'grincheux', '2');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('3', '1', 'J\'ai adoré !', 'blanche neige', '4');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('4', '1', 'Cool !', 'simplet', '3');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('5', '2', 'Pas mal comme entrée !', 'Samantha', '4');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('6', '2', 'Je préfère avec de la crème fraiche', 'Antoine', '2');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('7', '2', 'Je l\'ai faite en accompagnement et tout le monde à aimé', 'Paméla', '5');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('8', '3', 'J\'aime pas trop la combinaison avec le soja', 'Henri', '1');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('9', '3', 'Pareil, je trouve que le soja donne un gout trop bizarre', 'Jean', '2');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('10', '3', 'Osé et délicieux !', 'Lin', '5');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('11', '3', 'Pas mal', 'Bernard', '4');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('12', '3', 'pas terrible', 'Louis', '2');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('13', '4', 'Depuis le temps que je voulais savoir en faire, merci !', 'Louise', '5');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('14', '4', 'Meilleur recette de cheesecake', 'Martin', '5');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('15', '4', 'Manque un peu de sucre pour moi', 'Riton', '3');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('16', '5', 'ça à fait le plaisir de mes invités', 'Lisa', '5');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('17', '5', 'J\'adore le lapin et je cherchais une idée pour le préparer', 'Romain', '4');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('18', '5', 'Souple et savoureux !', 'Jean', '5');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('19', '6', 'Oh oui, une nouvelle idée de dessert', 'Marie', '5');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('20', '6', 'j\'adore les fruits rouges !', 'Melanie', '5');
INSERT INTO `luto`.`comment` (`comment_id`, `comment_recipe_id`, `comment_message`, `comment_author`, `recipe_rating`) VALUES ('21', '6', 'On peux faire mieux avec les mêmes ingrédients', 'Raymond', '2');
