INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('1', 'farine');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('2', 'beurre');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('3', 'sucre');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('4', 'jaune d\'oeuf');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('5', 'eau');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('6', 'sel');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('7', 'citrons de taille moyenne');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('8', 'oeufs');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('9', 'Maizena');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('10', 'levure chimique');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('11', 'pâtes (penne)');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('12', 'thon naturel');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('13', 'mayonnaise');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('14', 'asperges vertes');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('15', 'jus de citron');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('16', 'huile');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('17', 'curry en poudre');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('18', 'poivre');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('19', 'escalopes de poulet');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('20', 'gousse d\'ail haché très finement');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('21', 'crème fraiche');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('22', 'sauce soja');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('23', 'champignons de paris');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('24', 'fromage blanc');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('25', 'petits suisses');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('26', 'vanille');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('27', 'petits beurres (ou autres sablés)');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('28', 'sucre roux');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('29', 'Lesieur duo Huile & Beurre');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('30', 'cuisses de lapin');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('31', 'râble de lapin coupé en deux');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('32', 'lardons fumés');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('33', 'gousses d\'ail');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('34', 'échalotes');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('35', 'thym');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('36', 'tomates confites');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('37', 'pommes de terre charlottes');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('38', 'épinards frais');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('39', 'boules de crème glacée carte d\'or vanille de madagascar');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('40', 'fraises');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('41', 'framboises');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('42', 'myrtilles');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('43', 'groseilles');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('44', 'miel');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('45', 'cerises');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('46', 'meringues');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('47', 'blancs d\'oeufs');
INSERT INTO `luto`.`ingredient` (`ingredient_id`, `ingredient_name`) VALUES ('48', 'zeste de citron');
