INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('1', '1', '250', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('2', '1', '2', 'cuillères à soupe');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('3', '2', '125', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('4', '2', '1', 'noix');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('5', '3', '220', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('6', '4', '2');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('7', '5', '5', 'cl');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('8', '6', '1', 'pincée');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('9', '7', '4');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('10', '8', '3');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('11', '9', '1', 'cuillère à soupe');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('12', '10', '1/2', 'cuillère à café');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('13', '11', '300', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('14', '12', '200', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('15', '13', '4', 'c-à-s');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('16', '14', '1', 'bocal');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('17', '15', '1', 'c-à-s');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('18', '16', '1', 'c-à-s');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('19', '17', '1', 'c-à-c');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('20', '19', '2');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('21', '20', '1');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('22', '21', '2', 'grosses cuillères');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('23', '22', '1', 'c-à-s');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('24', '23', '2');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('25', '24', '500', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('26', '25', '2');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('27', '27', '1/3', 'de paquet');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('28', '28', '2', 'cuillères à soupe');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('29', '30', '2');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('30', '31', '1');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('31', '32', '200', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('32', '33', '8', '');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('33', '34', '2');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('34', '35', '2', 'petites branches');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('35', '36', '4');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('36', '37', '6');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('37', '38', '40', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('38', '39', '10');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('39', '40', '100', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('40', '41', '100', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('41', '42', '50', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('42', '43', '50', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('43', '44', '2', 'cuillères à café');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('44', '45', '4');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('45', '46', '4');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('46', '47', '2');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('47', '2', '50', 'g');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`) VALUES ('48', '48', '1');
INSERT INTO `luto`.`quantity` (`quantity_id`, `quantity_ingredient_id`, `quantity_number`, `quantity_type`) VALUES ('49', '15', '2', 'cuillère à soupe');
