INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('1', '1', '1', '1');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('1', '3', '2', '2');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('1', '5', '3', '3');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('1', '6', '4', '4');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('1', '7', '5', '5');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('1', '8', '6', '6');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('1', '9', '7', '7');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('1', '10', '8', '8');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('1', '11', '9', '9');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('1', '12', '10', '10');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('1', '46', '47', '11');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('2', '13', '11', '12');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('2', '14', '12', '13');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('2', '15', '13', '14');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('2', '16', '14', '15');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('2', '17', '15', '16');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('2', '18', '16', '17');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('2', '19', '17', '18');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('2', '6', '19');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('2', '18', '20');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('3', '20', '19', '21');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('3', '21', '20', '22');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('3', '4', '2', '23');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('3', '22', '21', '24');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('3', '23', '22', '25');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('3', '24', '23', '26');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('4', '25', '24', '27');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('4', '47', '2', '28');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('4', '10', '8', '29');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('4', '26', '25', '30');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('4', '3', '31');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('4', '2', '1', '32');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('4', '48', '48', '33');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('4', '49', '15', '34');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('4', '26', '35');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('4', '27', '27', '36');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('4', '28', '28', '37');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('5', '29', '38');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('5', '29', '30', '39');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('5', '30', '31', '40');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('5', '31', '32', '41');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('5', '32', '33', '42');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('5', '33', '34', '43');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('5', '34', '35', '44');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('5', '35', '36', '45');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('5', '36', '37', '46');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('5', '37', '38', '47');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('6', '38', '39', '48');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('6', '39', '40', '49');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('6', '40', '41', '50');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('6', '41', '42', '51');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('6', '42', '43', '52');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('6', '43', '44', '53');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('6', '44', '45', '54');
INSERT INTO `luto`.`recipe_ingredient_quantity` (`recipe_id`, `recipe_quantity_id`, `recipe_ingredient_id`, `recipe_ingredient_quantity_id`) VALUES ('6', '45', '46', '55');
