INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('1', 'Poulet');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('2', 'Creme');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('3', 'Soja');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('4', 'Tendre');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('5', 'Très facile');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('6', 'Bon marché');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('7', 'Tarte');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('8', 'Citron');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('9', 'Meringue');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('10', 'Facile');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('11', 'Moyen');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('12', 'Difficile');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('13', 'Très difficile');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('14', 'Accompagnement');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('15', 'Pates');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('16', 'Thon');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('17', 'Curry');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('18', 'Cheesecake');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('19', 'Moelleux');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('20', 'Fromage blanc');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('21', 'Lapin');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('22', 'Cocotte');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('23', 'Très facile - Facile');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('24', 'Facile - Moyen');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('25', 'Moyen - Difficile');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('26', 'Difficile - Très difficile');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('27', 'Fruits rouges');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('28', 'Framboises');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('29', 'Myrtilles');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('30', 'Fraises');
INSERT INTO `luto`.`tag` (`tag_id`, `tag_name`) VALUES ('31', 'Groseilles');